### ISSUE TITLE
Any user can perform any CRUD operation on messages or users

### ISSUE THREAD

**Issue by bclinthall** [feathersjs/feathers-chat#112]
I was experimenting a little to see how much is provided in the out of the box authentication middleware.  I noticed that the chat app allows any authenticated user to perform any CRUD operation on any service. I can change another user's password or message text, for example.
```javascript
let users = await client.service('users').find();
client.service('users').patch('43WhirE0yJr47G4J', {password: '123456'})
```
I'm concerned that somebody will get bitten by this.

**Comment by daffl** [comment]
This has been addressed in the latest chat which automatically generates a query schema that limits changes to the currently authenticated user.
