### ISSUE TITLE
oauth github sign in

### ISSUE THREAD

**Issue by 7NT** [feathersjs/feathers-chat#119]
works in my windows 7 chrome

does not work on windows 10: Chrome, Edge, and Firefox

Firfox message:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.githubassets.com/assets/frameworks-2fd1891c9e6292401a1a3de8bc3f747f.css. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.githubassets.com/assets/github-211e7a5168e3492fd5f3d4312f92593c.css. (Reason: CORS request did not succeed).[Learn More]

**Comment by daffl** [comment]
Can anybody else confirm this? There isn't anything making those requests from the Feathers side and it is the first time that I am hearing about this.

**Comment by mr019** [comment]
I also get a CORB warning on Chrome (win10):

stats.js:54 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.github.com/_private/browser/stats with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details

 After the authentication process I get redirected back to the login page
 http://localhost:3030/#

**Comment by daffl** [comment]
I'm going to close this. I demoed and helped set up GitHub integration multiple times with different browsers and operating systems and never had any issues. Many errors like the ones mentioned above often come from third party browser extensions or other browser specific settings.

**Comment by 7NT** [comment]
thanks, I will test it and let you know
