### ISSUE TITLE
How would the front end connect to a remote backend?

### ISSUE THREAD

**Issue by gnwankpa** [feathersjs/feathers-chat#122]
I see in this example (app.js) that there is socket connection to the backend but I am not seeing how the front end determines which socket it is connecting to... or the IP address where the server is located. I may have missed something but would like to know.

**Comment by daffl** [comment]
You can set the target URL when connecting to the socket. See https://docs.feathersjs.com/api/client/socketio.html#socketio-socket for more information.

**Comment by gnwankpa** [comment]
ah perfect, awesome youtube tutorial btw! Just wrapped it up.
