### ISSUE TITLE
Page is blank because scripts are blocked by browser security

### ISSUE THREAD

**Issue by muetsii** [feathersjs/feathers-chat#147]
### Steps to reproduce

1. clone the repo
2. npm install
3. npm start
4. enter http://localhost:3030/ in the browser

### Expected behavior
See something

### Actual behavior
The browser page is blank.

The page code is:
```
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0" />
    <title>FeathersJS chat</title>
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="base.css">
    <link rel="stylesheet" href="chat.css">
  </head>
  <body>
    <div id="app" class="flex flex-column"></div>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
    <script src="//unpkg.com/@feathersjs/client@^4.3.0/dist/feathers.js"></script>
    <script src="/socket.io/socket.io.js"></script>
    <script src="client.js"></script>
  </body>
</html>
```
#### Console errors (Chromium)
ERROR: Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

ERROR: localhost/:1 Refused to load the script 'https://unpkg.com/@feathersjs/client@%5E4.3.0/dist/feathers.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

ERROR client.js:5 Uncaught ReferenceError: feathers is not defined
    at client.js:5

#### Console errors (Firefox)

(sorry, I have firefox configured in Spanish)

Content Security Policy: No se puede procesar la directiva desconocida 'script-src-attr'

Ha fallado la carga del <script> con origen "http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js". localhost:3030:13:1

Ha fallado la carga del <script> con origen "http://unpkg.com/@feathersjs/client@%5E4.3.0/dist/feathers.js". localhost:3030:14:1

Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en inline (script-src). localhost:3030:1:1

Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js (script-src).

Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en http://unpkg.com/@feathersjs/client@%5E4.3.0/dist/feathers.js (script-src).

ReferenceError: feathers is not defined client.js:5:16

Content Security Policy: Actualizando solicitud insegura 'ws://localhost:3030/socket.io/?EIO=3&transport=websocket&sid=V884JLfBmOGKZaW9AAAE' para usar 'wss'

Firefox no puede establecer una conexión con el servidor en wss://localhost:3030/socket.io/?EIO=3&transport=websocket&sid=V884JLfBmOGKZaW9AAAE. socket.io.js:8:6159

### System configuration

**Module versions** (especially the part that's not working): N/A?

**NodeJS version**: 12.18.3

**Operating System**: Debian GNU/Linux

**Browser Version**: Firefox 68.11.0esr (64-bit); Chromium 83.0.4103.116 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit)

**React Native Version**: ?

**Module Loader**: ?

(sorry, I'm not very competent in frontend, I guess the problem is easy because I could not find any other issue on it)

**Comment by daffl** [comment]
I am not able to reproduce this in any browser and am hearing about this for the first time. This must be some setting in your browser content policies, a browser plugin you enabled or a proxy server that strips out the `allow-origin` header that is causing this.

**Comment by muetsii** [comment]
Some plugin blocking the script I would expect from Firefox, but I don't usually use Chromium, and I don't have anything strange installed.

Also tried Epiphany (or Gnome Web), and got something similar

```
[Error] Refused to load https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Refused to load https://unpkg.com/@feathersjs/client@^4.3.0/dist/feathers.js because it does not appear in the script-src directive of the Content Security Policy.
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (base.css, line 0)
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (chat.css, line 0)
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (socket.io.js, line 0)
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (client.js, line 0)
[Error] Failed to load resource: Error performing TLS handshake: An unexpected TLS packet was received. (favicon.ico, line 0)
```

So, I tried three different browsers with three different engines, more or less same issue.

On the other hand, this seems to happen only to me :|

**Comment by muetsii** [comment]
And the address of the socket.io plugin gives me 404

https://socket.io/socket.io.js

**Comment by daffl** [comment]
The script address is `http://localhost:3030/socket.io/socket.io.js`. Aside from that, I'm not sure if we can help you here. This looks like a problem very specific to your system (looking at the SSL error your OpenSSL configuration may be borked). I'd recommend to try it on a different operating system in a VM to see if it persists.

**Comment by malikdoksoz** [comment]
<img width="1422" alt="Ekran Resmi 2020-09-26 00 36 12" src="https://user-images.githubusercontent.com/26676061/94318038-4965c000-ff90-11ea-9c7c-1ed18deeb1d7.png">

**Comment by ljieyao** [comment]
i have the same issue here. any solutions?

**Comment by daffl** [comment]
You can add

```js
app.use((req, res, next) => {
  res.header('Content-Security-Policy', 'script-src 'self' unpkg.com cdnjs.cloudflare.com');
  next();
});
```

To `src/app.js`.

What I don't understand is why setting the equivalent meta tag in `public/index.html` does _not_ seem to work:

```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self' unpkg.com cdnjs.cloudflare.com">
```

Content security policies are a complicated not really Feathers specific topic. More info can be found at [content-security-policy.com](https://content-security-policy.com/) and [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (both did not answer the question why my `meta` tag does not work though).

**Comment by daffl** [comment]
Ok, figured it out, it was the new version of helmet. In your `src/app.js|ts` change

```js
app.use(helmet());
```

To

```js
app.use(helmet({
  contentSecurityPolicy: false
}));
```

This will no longer happen in a newly generated application.
