### ISSUE TITLE
Initial click on "Sign up and log in" fails with No record found for id '1'

### ISSUE THREAD

**Issue by cirosantilli** [feathersjs/feathers-chat#185]
feathers-chat fd729a47c57f9e6170cc1fa23cee0c84a004feb5 Ubuntu 20.10 Node 14.60.0 Chromium 89.0.4389.90 clone then:

```
npm install
npm start
```

visit http://localhost:3030/ enter:

- email: `a@a`
- password `a`

and click "Sign up and log in".

Instead of working, the browser shows a JavaScript error on the console:

```
{
    "name": "NotFound",
    "message": "No record found for id '1'",
    "code": 404,
    "className": "not-found",
    "errors": {}
}
```

and you remain on the page without any visible GUI error.

This can be worked around by first clicking "Login" (which gives "There was an error: Invalid login" as expected), but then doing a second attempt at "Sign up and log in" works and redirects you to the chat as expected

**Comment by daffl** [comment]
Tested with the latest version of the chat and this should be fixed now.
