### ISSUE TITLE
Test configuration not working

### ISSUE THREAD

**Issue by nomuna** [feathersjs/feathers-chat#214]
### Steps to reproduce

Check out the project and run the tests more than once. 

I am observing this issue on a windows 10 machine with node v14.18.1.

Tests are not using the _test/data_ folder as configured in the _config/test.json_ You will get unique constraint violation for the email field for the created users.

I think the _nedb_ configuration is wrong. Or even worse the _app.get("nedb")_ is ignoring the _NODE_ENV_ set... Which means that the _@feathers/configuration_ is buggy.

**Comment by daffl** [comment]
This should work now with the latest chat which uses SQLite by default instead.
