### ISSUE TITLE
Updating the elm-chat for Elm 0.17

### ISSUE THREAD

**Issue by greyarch** [feathersjs/feathers-chat#22]
Are there plans to update the Elm version of the app for Elm 0.17?

**Comment by daffl** [comment]
@benjick made the original demo (and there was an issue for creating a guide for it at https://github.com/feathersjs/feathers-docs/issues/99). If he is busy somebody else needs to make it happen.

**Comment by greyarch** [comment]
I created a PR with elm-chat ported to Elm 0.17. Will close this issue.
