### ISSUE TITLE
oauth github fails with `error: BadRequest: validation failed`

### ISSUE THREAD

**Issue by s-light** [feathersjs/feathers-chat#237]
### Steps to reproduce

- clone this repository and setup as described in readme.
- [follow tutorial](https://feathersjs.com/guides/basics/login.html#login-with-github) to setup github 
- replace `<Client ID>` and `<Client Secret>` in `config/default.json`
- start app `npm run dev`
- go to [`http://localhost:3030/#`](http://localhost:3030/#)
- click the `login with github` button
- authentication on github.com is successful

### Expected behavior
- return to chat app logged in

### Actual behavior
- login in chat app fails:
``` js
error: BadRequest: validation failed
    at UserService.<anonymous> (/path/to/folder/feathers-chat/feathers-chat-ts/node_modules/@feathersjs/schema/lib/hooks/validate.js:47:35)
error: Data: [
  {
    instancePath: '/email',
    schemaPath: '#/properties/email/type',
    keyword: 'type',
    params: { type: 'string' },
    message: 'must be string'
  }
]
```

### System configuration

**NodeJS version**:
v19.7.0

**Operating System**:
kubuntu 22.10

**Browser Version**:
firefox 110.0.1 (64-bit)

**Comment by s-light** [comment]
maybe it is similar to  #135 ?
but i *think* i have my mail available...

**Comment by daffl** [comment]
Ah, that does happen when the email is protected on GitHub. I think that was why there was a username as a fallback.

**Comment by s-light** [comment]
so it would make sens to add this fallback to the example?!
as i am in a early exploring state i do not really now how to handle this...

**Comment by FossPrime** [comment]
@s-light fix merged

**Comment by tesar27** [comment]
I have found an issue implementing the same guide.
The user schema expects githubId as a string, but indeed it is a number, hence correcting this part 
`githubId: Type.Optional(Type.Number()),` solved the issue.
Hope it helps and still useful
