### ISSUE TITLE
something seems wrong with global hooks

### ISSUE THREAD

**Issue by akralj** [feathersjs/feathers-chat#28]
hi,
im copying this projects dir structure for a project of mine and came accross the global hooks in:
https://github.com/feathersjs/feathers-chat/blob/7d12469ba23dcf57bdcb3e34fd8a758a05a066dd/src/hooks/index.js#L9
it seems there are not used anywhere, and the export function seems wrong. shouldn't it be module.exports and doesn't it need a next callback, like it is used in the hooks under the services?
have a great day

**Comment by daffl** [comment]
The exports function should be right but you are correct, it is not used anywhere. Having a callback in a hook is optional and will also be deprecated in the future (instead you can just return a promise as documented [here](http://docs.feathersjs.com/hooks/usage.html#promises)).

**Comment by akralj** [comment]
thanks, that explains it.
