### ISSUE TITLE
How to update the number of currently connected users?

### ISSUE THREAD

**Issue by frapik99** [feathersjs/feathers-chat#45]
Hi,
first of all thanks for this great example. I would ask if possible, if someone can tell me how to make possible that if a user disconnects the number of total user can be updated for all the other users already connected.

Thanks

**Comment by eddyystop** [comment]
Its possible with auth v1 using `app.log('on', ...)` and `app.log('off', ...)`.

I'm not sure its that easy with v0.7. Sometime custom may be needed.

**Comment by FossPrime** [comment]
This was solved sometime in the last five years... Closing
