### ISSUE TITLE
on what url do i see the chat app working ?

### ISSUE THREAD

**Issue by jpca999** [feathersjs/feathers-chat#58]

**Comment by emp3ror** [comment]
as shown by readme
after doing `npm start` should show in http://localhost:3030/
but it just shows welcome msg only

**Comment by kfern** [comment]
Hi!

There are some index. Look at public folder. Javascript index is in http://localhost:3030/public/vanilla

Salu2

**Comment by kfern** [comment]
Sorry. http://localhost:3030/vanilla/

**Comment by emp3ror** [comment]
thanks it show login screen, may be should update readme :D

**Comment by kfern** [comment]
It's a good idea ;-)
