### ISSUE TITLE
Add deploy to heroku button

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-chat#7]

**Comment by diego-vieira** [comment]
@ekryski will send a PR in a few.

**Comment by diego-vieira** [comment]
Just sent this [PR](https://github.com/feathersjs/feathers-chat/pull/20/files) but something is up with JWT. Perhaps because heroku won't allow us to use NEDB, instead we might need to use Mongo or PG when deploying.

Will investigate.
https://powerful-caverns-43820.herokuapp.com

**Comment by daffl** [comment]
Closed via #20
