### ISSUE TITLE
connect to mongodb

### ISSUE THREAD

**Issue by jebraieili** [feathersjs/feathers-chat#72]
Hello,
First of all, this is a great framework, and i like this example. But How can I connect to the Mongo db instead of nedb on this example.thanks

**Comment by daffl** [comment]
Have you tried just picking MongoDB instead of NeDB when generating the services?

**Comment by jebraieili** [comment]
Yes i tried,but i got this error "Error: options.service does not exist." ,this is my code in "users/users.service.js"

const hooks = require('./users.hooks');
const filters = require('./users.filters');
const MongoClient = require('mongodb').MongoClient;
const mongoService = require('feathers-mongodb');
module.exports = function () {
  const app = this;
  MongoClient.connect( 'mongodb://localhost:27017/mydb', function(err, db) {
    if (err) throw err;
    const Model=db.collection('users');
    const paginate = app.get('paginate');
    const options = {
      name: 'users',
      Model,
      paginate
    };
    app.use('/users', mongoService(options));
    const service = app.service('users');
    service.hooks(hooks);

    if (service.filter) {
      service.filter(filters);
    }
  });
};

**Comment by daffl** [comment]
That does not look like what the generator would do though? Also, what is the stack trace of the error (it doesn't look like it is happening here)?

**Comment by jebraieili** [comment]
is that code wrong for using mongo db?

**Comment by daffl** [comment]
Not wrong necessarily but if you use it in the generated application the `notFound` middleware will be registered before the MongoDB connection resolves and you'll always get a 404. The generated connection will prevent this from happening by essentially doing this:

```js
const hooks = require('./users.hooks');
const filters = require('./users.filters');
const MongoClient = require('mongodb').MongoClient;
const mongoService = require('feathers-mongodb');
module.exports = function () {
  const app = this;

  const Model=db.collection('users');
  const paginate = app.get('paginate');
  const options = {
    name: 'users',
    paginate
  };
  app.use('/users', mongoService(options));
  const service = app.service('users');
  service.hooks(hooks);
  if (service.filter) {
    service.filter(filters);
  }

  MongoClient.connect( 'mongodb://localhost:27017/mydb', function(err, db) {
    if (err) throw err;
    service.Model = db.collection('users');
  });
};
```
