### ISSUE TITLE
It's stopped to work after 'feathersjs upgrade'

### ISSUE THREAD

**Issue by TimurAditazz** [feathersjs/feathers-chat#76]
Looks like websocket messages has stopped to dispatch or so

**Comment by daffl** [comment]
I just clone latest master, ran `npm install && npm start` and everything worked fine using the `/vanilla` example. Make sure you `channels.js` looks the same as https://github.com/feathersjs/feathers-chat/blob/master/src/channels.js

**Comment by TimurAditazz** [comment]
what about `feathers upgrade`
it adds excessive express
_const app = express(express(feathers()));_

that is the minor issue

**Comment by TimurAditazz** [comment]
my original issue can be reproduced on commit 3da1f6ae842c9c5195e4bbe2ef746630275a4f6c created couple days ago
`feathers upgrade` makes it crazy

not sure how the issue important
I am thinking how I can upgrade my old project to latest feathersjs, looks like I should recreate it from scratch

**Comment by daffl** [comment]
Well you shouldn't run `feathers upgrade` twice. I'll make it throw an error if that is the case.

**Comment by TimurAditazz** [comment]
That addresses the minor issue, right?

**Comment by daffl** [comment]
I'm not exactly sure what the issue is. In order to get events you have to follow the [migration guide](http://buzzard.docs.feathersjs.com/migrating.html#quick-upgrade) and add the `channels.js` file.

**Comment by TimurAditazz** [comment]
Yep, I am not familiar with the feathersjs so I was a little distracted. Would be good to add some notice at end of a upgrade process about some manual care required. I thought it should be fully automatic
