### ISSUE TITLE
I got error when I try to authenticate

### ISSUE THREAD

**Issue by lagmanzaza** [feathersjs/feathers-chat#78]
![screen shot 2560-12-31 at 04 09 36](https://user-images.githubusercontent.com/5283709/34457339-888cb58c-ede0-11e7-8065-6682cce411e4.png)

**Comment by daffl** [comment]
Can you share your full application? It looks like you registered a hook that is not a function.

**Comment by lagmanzaza** [comment]
I clone it from this repository then run on my local server but it's not work

**Comment by daffl** [comment]
What operating system, Node and npm version?

**Comment by lagmanzaza** [comment]
I can fix it by removing authenticate() in create Hook in user service

**Comment by daffl** [comment]
Ah yes, I just noticed that, too and fixed it via https://github.com/feathersjs/feathers-chat/commit/56762c2540cfcb53ead0e595216ceabbcd0df08a

**Comment by lagmanzaza** [comment]
Thank you very much
