### ISSUE TITLE
Async Error Hook Gravatar

### ISSUE THREAD

**Issue by xOwl420** [feathersjs/feathers-chat#84]
Hello,

when i modify my gravatar.js code to the Tutorial Code i get a fail when i start the server.

return async context => { ^^^^^^^

When i remove the async in the gravatar.js the server starts normally..

Someone have a clue?

**Comment by daffl** [comment]
The [prerequesites](https://docs.feathersjs.com/guides/basics/setup.html#prerequisites) mention that you need Node (`node --version`) 8 or later for all the examples in the guides to work.
