### ISSUE TITLE
The index file has a random script closing tag in it's body

### ISSUE THREAD

**Issue by contis2908** [feathersjs/feathers-chat#85]
I might be wrong but it looks to me as if the example of the index.html file for the chat application has a random </script> closing tag in its body.

**Comment by daffl** [comment]
It does indeed. You can make a pull request with the correct content by clicking the [Edit this page link](https://github.com/feathersjs/docs/edit/master/guides/chat/frontend.md).

**Comment by daffl** [comment]
Thank you for the documentation PR. I fixed it in this repository as well.
