### ISSUE TITLE
npm test on process-message hook is returning an error "Cannot read property 'text' of undefined"

### ISSUE THREAD

**Issue by houssami** [feathersjs/feathers-chat#88]
Following the tutorial to reproduce the error:

The error occurs on the "Processing data" section of the tutorial after adding the process-message.js hook and copying the new code for that file from the tutorial.

The npm test error seems to be occurring on line: `if(!data.text) {`

test error: 5 passing (71ms)
  1 failing

  1) 'process-message' hook
       runs the hook:
     TypeError: Cannot read property 'text' of undefined
      at Object.<anonymous> (src/hooks/process-message.js:9:14)
      at promise.then.hookObject (node_modules/@feathersjs/commons/lib/hooks.js:174:73)
      at <anonymous>

Note: If you proceed with the tutorial the same issue will occur with similar hooks ex. gravatar.

env:
node v8.10.0
npm 5.6.0
feathers 3.6.1
redhat el 7.4

**Comment by daffl** [comment]
Once the files is updated, the standard hook tests will fail. Making them all pass is what the [writing tests chapter](https://docs.feathersjs.com/guides/chat/testing.html) is covering.
