### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [feathersjs/feathers-chat#89]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by jbeguna04** [comment]
Thank you please allow me to send suggestions here

**Comment by daffl** [comment]
Absolutely. I'm going to close this issue though to keep them curated. If you have any suggestions, a new issue or - even better - pull request is always welcome of course 😄
